version: '3.9'
services:
  # PostgreSQL server
#  postgres:
#    image: "postgres:latest"
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: db_duke
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 7654
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U session"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: session